### ISSUE TITLE
Redirect URI mismatch error

### ISSUE THREAD

**Issue by crowesn** [uclibs/orcid#2]
Found [this](https://github.com/intridea/omniauth-oauth2/issues/81#issuecomment-151038559) and I think it's related - looking at pinning to earlier version of omniauth-oauth2.

**Comment by crowesn** [comment]
Related https://github.com/uclibs/scholar_uc/issues/600

**Comment by crowesn** [comment]
@13miciunasl This should solve your problem, please check out the branch and check locally.

**Comment by newmanld** [comment]
Good catch @crowesn  - “Found thishttps://github.com/intridea/omniauth-oauth2/issues/81#issuecomment-151038559”
